import type { IssueCategory } from '@/shared/types';


export const CATEGORY_COLORS: Record<IssueCategory, { bg: string; text: string; hex: string }> = {
  education:   { bg: 'bg-blue-100',    text: 'text-blue-800',    hex: '#3B82F6' },
  housing:     { bg: 'bg-green-100',   text: 'text-green-800',   hex: '#10B981' },
  transport:   { bg: 'bg-yellow-100',  text: 'text-yellow-800',  hex: '#F59E0B' },
  safety:      { bg: 'bg-red-100',     text: 'text-red-800',     hex: '#EF4444' },
  environment: { bg: 'bg-emerald-100', text: 'text-emerald-800', hex: '#059669' },
  economy:     { bg: 'bg-purple-100',  text: 'text-purple-800',  hex: '#8B5CF6' },
  welfare:     { bg: 'bg-pink-100',    text: 'text-pink-800',    hex: '#EC4899' },
  governance:  { bg: 'bg-gray-100',    text: 'text-gray-800',    hex: '#6B7280' },
  healthcare:  { bg: 'bg-teal-100',    text: 'text-teal-800',    hex: '#14B8A6' },
  culture:     { bg: 'bg-orange-100',  text: 'text-orange-800',  hex: '#F97316' },
};

export const CATEGORY_EMOJIS: Record<IssueCategory, string> = {
  education:   '🏫',
  housing:     '🏠',
  transport:   '🚗',
  safety:      '🛡️',
  environment: '🌳',
  economy:     '💼',
  welfare:     '🤝',
  governance:  '🏛️',
  healthcare:  '🏥',
  culture:     '🎭',
};

export const ISSUE_CATEGORIES: IssueCategory[] = [
  'education',
  'housing',
  'transport',
  'safety',
  'environment',
  'economy',
  'welfare',
  'governance',
  'healthcare',
  'culture',
];


export interface ElectionDistrict {
  name: string;
  shortName: string;
  nameEn: string;
  districts: { name: string; nameEn: string }[];
}

export const ELECTION_DISTRICTS: Record<string, ElectionDistrict> = {
  seoul: {
    name: '서울특별시', shortName: '서울', nameEn: 'Seoul',
    districts: [
      { name: '종로구', nameEn: 'Jongno-gu' },
      { name: '중구', nameEn: 'Jung-gu' },
      { name: '용산구', nameEn: 'Yongsan-gu' },
      { name: '성동구', nameEn: 'Seongdong-gu' },
      { name: '광진구', nameEn: 'Gwangjin-gu' },
      { name: '동대문구', nameEn: 'Dongdaemun-gu' },
      { name: '중랑구', nameEn: 'Jungnang-gu' },
      { name: '성북구', nameEn: 'Seongbuk-gu' },
      { name: '강북구', nameEn: 'Gangbuk-gu' },
      { name: '도봉구', nameEn: 'Dobong-gu' },
      { name: '노원구', nameEn: 'Nowon-gu' },
      { name: '은평구', nameEn: 'Eunpyeong-gu' },
      { name: '서대문구', nameEn: 'Seodaemun-gu' },
      { name: '마포구', nameEn: 'Mapo-gu' },
      { name: '양천구', nameEn: 'Yangcheon-gu' },
      { name: '강서구', nameEn: 'Gangseo-gu' },
      { name: '구로구', nameEn: 'Guro-gu' },
      { name: '금천구', nameEn: 'Geumcheon-gu' },
      { name: '영등포구', nameEn: 'Yeongdeungpo-gu' },
      { name: '동작구', nameEn: 'Dongjak-gu' },
      { name: '관악구', nameEn: 'Gwanak-gu' },
      { name: '서초구', nameEn: 'Seocho-gu' },
      { name: '강남구', nameEn: 'Gangnam-gu' },
      { name: '송파구', nameEn: 'Songpa-gu' },
      { name: '강동구', nameEn: 'Gangdong-gu' },
    ],
  },
  busan: {
    name: '부산광역시', shortName: '부산', nameEn: 'Busan',
    districts: [
      { name: '중구', nameEn: 'Jung-gu' },
      { name: '서구', nameEn: 'Seo-gu' },
      { name: '동구', nameEn: 'Dong-gu' },
      { name: '영도구', nameEn: 'Yeongdo-gu' },
      { name: '부산진구', nameEn: 'Busanjin-gu' },
      { name: '동래구', nameEn: 'Dongnae-gu' },
      { name: '남구', nameEn: 'Nam-gu' },
      { name: '북구', nameEn: 'Buk-gu' },
      { name: '해운대구', nameEn: 'Haeundae-gu' },
      { name: '사하구', nameEn: 'Saha-gu' },
      { name: '금정구', nameEn: 'Geumjeong-gu' },
      { name: '강서구', nameEn: 'Gangseo-gu' },
      { name: '연제구', nameEn: 'Yeonje-gu' },
      { name: '수영구', nameEn: 'Suyeong-gu' },
      { name: '사상구', nameEn: 'Sasang-gu' },
      { name: '기장군', nameEn: 'Gijang-gun' },
    ],
  },
  daegu: {
    name: '대구광역시', shortName: '대구', nameEn: 'Daegu',
    districts: [
      { name: '중구', nameEn: 'Jung-gu' },
      { name: '동구', nameEn: 'Dong-gu' },
      { name: '서구', nameEn: 'Seo-gu' },
      { name: '남구', nameEn: 'Nam-gu' },
      { name: '북구', nameEn: 'Buk-gu' },
      { name: '수성구', nameEn: 'Suseong-gu' },
      { name: '달서구', nameEn: 'Dalseo-gu' },
      { name: '달성군', nameEn: 'Dalseong-gun' },
      { name: '군위군', nameEn: 'Gunwi-gun' },
    ],
  },
  incheon: {
    name: '인천광역시', shortName: '인천', nameEn: 'Incheon',
    districts: [
      { name: '미추홀구', nameEn: 'Michuhol-gu' },
      { name: '연수구', nameEn: 'Yeonsu-gu' },
      { name: '남동구', nameEn: 'Namdong-gu' },
      { name: '부평구', nameEn: 'Bupyeong-gu' },
      { name: '계양구', nameEn: 'Gyeyang-gu' },
      { name: '서구', nameEn: 'Seo-gu' },
      { name: '제물포구', nameEn: 'Jemulpo-gu' },
      { name: '영종구', nameEn: 'Yeongjong-gu' },
      { name: '검단구', nameEn: 'Geomdan-gu' },
      { name: '강화군', nameEn: 'Ganghwa-gun' },
      { name: '옹진군', nameEn: 'Ongjin-gun' },
    ],
  },
  gwangju: {
    name: '광주광역시', shortName: '광주', nameEn: 'Gwangju',
    districts: [
      { name: '동구', nameEn: 'Dong-gu' },
      { name: '서구', nameEn: 'Seo-gu' },
      { name: '남구', nameEn: 'Nam-gu' },
      { name: '북구', nameEn: 'Buk-gu' },
      { name: '광산구', nameEn: 'Gwangsan-gu' },
    ],
  },
  daejeon: {
    name: '대전광역시', shortName: '대전', nameEn: 'Daejeon',
    districts: [
      { name: '동구', nameEn: 'Dong-gu' },
      { name: '중구', nameEn: 'Jung-gu' },
      { name: '서구', nameEn: 'Seo-gu' },
      { name: '유성구', nameEn: 'Yuseong-gu' },
      { name: '대덕구', nameEn: 'Daedeok-gu' },
    ],
  },
  ulsan: {
    name: '울산광역시', shortName: '울산', nameEn: 'Ulsan',
    districts: [
      { name: '중구', nameEn: 'Jung-gu' },
      { name: '남구', nameEn: 'Nam-gu' },
      { name: '동구', nameEn: 'Dong-gu' },
      { name: '북구', nameEn: 'Buk-gu' },
      { name: '울주군', nameEn: 'Ulju-gun' },
    ],
  },
  sejong: {
    name: '세종특별자치시', shortName: '세종', nameEn: 'Sejong',
    districts: [],
  },
  gyeonggi: {
    name: '경기도', shortName: '경기', nameEn: 'Gyeonggi',
    districts: [
      { name: '수원시', nameEn: 'Suwon-si' },
      { name: '고양시', nameEn: 'Goyang-si' },
      { name: '용인시', nameEn: 'Yongin-si' },
      { name: '성남시', nameEn: 'Seongnam-si' },
      { name: '부천시', nameEn: 'Bucheon-si' },
      { name: '화성시', nameEn: 'Hwaseong-si' },
      { name: '안산시', nameEn: 'Ansan-si' },
      { name: '남양주시', nameEn: 'Namyangju-si' },
      { name: '안양시', nameEn: 'Anyang-si' },
      { name: '평택시', nameEn: 'Pyeongtaek-si' },
      { name: '시흥시', nameEn: 'Siheung-si' },
      { name: '파주시', nameEn: 'Paju-si' },
      { name: '의정부시', nameEn: 'Uijeongbu-si' },
      { name: '김포시', nameEn: 'Gimpo-si' },
      { name: '광주시', nameEn: 'Gwangju-si' },
      { name: '광명시', nameEn: 'Gwangmyeong-si' },
      { name: '군포시', nameEn: 'Gunpo-si' },
      { name: '하남시', nameEn: 'Hanam-si' },
      { name: '오산시', nameEn: 'Osan-si' },
      { name: '양주시', nameEn: 'Yangju-si' },
      { name: '이천시', nameEn: 'Icheon-si' },
      { name: '구리시', nameEn: 'Guri-si' },
      { name: '안성시', nameEn: 'Anseong-si' },
      { name: '포천시', nameEn: 'Pocheon-si' },
      { name: '의왕시', nameEn: 'Uiwang-si' },
      { name: '여주시', nameEn: 'Yeoju-si' },
      { name: '동두천시', nameEn: 'Dongducheon-si' },
      { name: '과천시', nameEn: 'Gwacheon-si' },
      { name: '가평군', nameEn: 'Gapyeong-gun' },
      { name: '양평군', nameEn: 'Yangpyeong-gun' },
      { name: '연천군', nameEn: 'Yeoncheon-gun' },
    ],
  },
  gangwon: {
    name: '강원특별자치도', shortName: '강원', nameEn: 'Gangwon',
    districts: [
      { name: '춘천시', nameEn: 'Chuncheon-si' },
      { name: '원주시', nameEn: 'Wonju-si' },
      { name: '강릉시', nameEn: 'Gangneung-si' },
      { name: '동해시', nameEn: 'Donghae-si' },
      { name: '태백시', nameEn: 'Taebaek-si' },
      { name: '속초시', nameEn: 'Sokcho-si' },
      { name: '삼척시', nameEn: 'Samcheok-si' },
      { name: '홍천군', nameEn: 'Hongcheon-gun' },
      { name: '횡성군', nameEn: 'Hoengseong-gun' },
      { name: '영월군', nameEn: 'Yeongwol-gun' },
      { name: '평창군', nameEn: 'Pyeongchang-gun' },
      { name: '정선군', nameEn: 'Jeongseon-gun' },
      { name: '철원군', nameEn: 'Cheorwon-gun' },
      { name: '화천군', nameEn: 'Hwacheon-gun' },
      { name: '양구군', nameEn: 'Yanggu-gun' },
      { name: '인제군', nameEn: 'Inje-gun' },
      { name: '고성군', nameEn: 'Goseong-gun' },
      { name: '양양군', nameEn: 'Yangyang-gun' },
    ],
  },
  chungbuk: {
    name: '충청북도', shortName: '충북', nameEn: 'Chungbuk',
    districts: [
      { name: '청주시', nameEn: 'Cheongju-si' },
      { name: '충주시', nameEn: 'Chungju-si' },
      { name: '제천시', nameEn: 'Jecheon-si' },
      { name: '보은군', nameEn: 'Boeun-gun' },
      { name: '옥천군', nameEn: 'Okcheon-gun' },
      { name: '영동군', nameEn: 'Yeongdong-gun' },
      { name: '증평군', nameEn: 'Jeungpyeong-gun' },
      { name: '진천군', nameEn: 'Jincheon-gun' },
      { name: '괴산군', nameEn: 'Goesan-gun' },
      { name: '음성군', nameEn: 'Eumseong-gun' },
      { name: '단양군', nameEn: 'Danyang-gun' },
    ],
  },
  chungnam: {
    name: '충청남도', shortName: '충남', nameEn: 'Chungnam',
    districts: [
      { name: '천안시', nameEn: 'Cheonan-si' },
      { name: '공주시', nameEn: 'Gongju-si' },
      { name: '보령시', nameEn: 'Boryeong-si' },
      { name: '아산시', nameEn: 'Asan-si' },
      { name: '서산시', nameEn: 'Seosan-si' },
      { name: '논산시', nameEn: 'Nonsan-si' },
      { name: '계룡시', nameEn: 'Gyeryong-si' },
      { name: '당진시', nameEn: 'Dangjin-si' },
      { name: '금산군', nameEn: 'Geumsan-gun' },
      { name: '부여군', nameEn: 'Buyeo-gun' },
      { name: '서천군', nameEn: 'Seocheon-gun' },
      { name: '청양군', nameEn: 'Cheongyang-gun' },
      { name: '홍성군', nameEn: 'Hongseong-gun' },
      { name: '예산군', nameEn: 'Yesan-gun' },
      { name: '태안군', nameEn: 'Taean-gun' },
    ],
  },
  jeonbuk: {
    name: '전북특별자치도', shortName: '전북', nameEn: 'Jeonbuk',
    districts: [
      { name: '전주시', nameEn: 'Jeonju-si' },
      { name: '군산시', nameEn: 'Gunsan-si' },
      { name: '익산시', nameEn: 'Iksan-si' },
      { name: '정읍시', nameEn: 'Jeongeup-si' },
      { name: '남원시', nameEn: 'Namwon-si' },
      { name: '김제시', nameEn: 'Gimje-si' },
      { name: '완주군', nameEn: 'Wanju-gun' },
      { name: '진안군', nameEn: 'Jinan-gun' },
      { name: '무주군', nameEn: 'Muju-gun' },
      { name: '장수군', nameEn: 'Jangsu-gun' },
      { name: '임실군', nameEn: 'Imsil-gun' },
      { name: '순창군', nameEn: 'Sunchang-gun' },
      { name: '고창군', nameEn: 'Gochang-gun' },
      { name: '부안군', nameEn: 'Buan-gun' },
    ],
  },
  jeonnam: {
    name: '전라남도', shortName: '전남', nameEn: 'Jeonnam',
    districts: [
      { name: '목포시', nameEn: 'Mokpo-si' },
      { name: '여수시', nameEn: 'Yeosu-si' },
      { name: '순천시', nameEn: 'Suncheon-si' },
      { name: '나주시', nameEn: 'Naju-si' },
      { name: '광양시', nameEn: 'Gwangyang-si' },
      { name: '담양군', nameEn: 'Damyang-gun' },
      { name: '곡성군', nameEn: 'Gokseong-gun' },
      { name: '구례군', nameEn: 'Gurye-gun' },
      { name: '고흥군', nameEn: 'Goheung-gun' },
      { name: '보성군', nameEn: 'Boseong-gun' },
      { name: '화순군', nameEn: 'Hwasun-gun' },
      { name: '장흥군', nameEn: 'Jangheung-gun' },
      { name: '강진군', nameEn: 'Gangjin-gun' },
      { name: '해남군', nameEn: 'Haenam-gun' },
      { name: '영암군', nameEn: 'Yeongam-gun' },
      { name: '무안군', nameEn: 'Muan-gun' },
      { name: '함평군', nameEn: 'Hampyeong-gun' },
      { name: '영광군', nameEn: 'Yeonggwang-gun' },
      { name: '장성군', nameEn: 'Jangseong-gun' },
      { name: '완도군', nameEn: 'Wando-gun' },
      { name: '진도군', nameEn: 'Jindo-gun' },
      { name: '신안군', nameEn: 'Sinan-gun' },
    ],
  },
  gyeongbuk: {
    name: '경상북도', shortName: '경북', nameEn: 'Gyeongbuk',
    districts: [
      { name: '포항시', nameEn: 'Pohang-si' },
      { name: '경주시', nameEn: 'Gyeongju-si' },
      { name: '김천시', nameEn: 'Gimcheon-si' },
      { name: '안동시', nameEn: 'Andong-si' },
      { name: '구미시', nameEn: 'Gumi-si' },
      { name: '영주시', nameEn: 'Yeongju-si' },
      { name: '영천시', nameEn: 'Yeongcheon-si' },
      { name: '상주시', nameEn: 'Sangju-si' },
      { name: '문경시', nameEn: 'Mungyeong-si' },
      { name: '경산시', nameEn: 'Gyeongsan-si' },
      { name: '의성군', nameEn: 'Uiseong-gun' },
      { name: '청송군', nameEn: 'Cheongsong-gun' },
      { name: '영양군', nameEn: 'Yeongyang-gun' },
      { name: '영덕군', nameEn: 'Yeongdeok-gun' },
      { name: '청도군', nameEn: 'Cheongdo-gun' },
      { name: '고령군', nameEn: 'Goryeong-gun' },
      { name: '성주군', nameEn: 'Seongju-gun' },
      { name: '칠곡군', nameEn: 'Chilgok-gun' },
      { name: '예천군', nameEn: 'Yecheon-gun' },
      { name: '봉화군', nameEn: 'Bonghwa-gun' },
      { name: '울진군', nameEn: 'Uljin-gun' },
      { name: '울릉군', nameEn: 'Ulleung-gun' },
    ],
  },
  gyeongnam: {
    name: '경상남도', shortName: '경남', nameEn: 'Gyeongnam',
    districts: [
      { name: '창원시', nameEn: 'Changwon-si' },
      { name: '진주시', nameEn: 'Jinju-si' },
      { name: '통영시', nameEn: 'Tongyeong-si' },
      { name: '사천시', nameEn: 'Sacheon-si' },
      { name: '김해시', nameEn: 'Gimhae-si' },
      { name: '밀양시', nameEn: 'Miryang-si' },
      { name: '거제시', nameEn: 'Geoje-si' },
      { name: '양산시', nameEn: 'Yangsan-si' },
      { name: '의령군', nameEn: 'Uiryeong-gun' },
      { name: '함안군', nameEn: 'Haman-gun' },
      { name: '창녕군', nameEn: 'Changnyeong-gun' },
      { name: '고성군', nameEn: 'Goseong-gun' },
      { name: '남해군', nameEn: 'Namhae-gun' },
      { name: '하동군', nameEn: 'Hadong-gun' },
      { name: '산청군', nameEn: 'Sancheong-gun' },
      { name: '함양군', nameEn: 'Hamyang-gun' },
      { name: '거창군', nameEn: 'Geochang-gun' },
      { name: '합천군', nameEn: 'Hapcheon-gun' },
    ],
  },
  jeju: {
    name: '제주특별자치도', shortName: '제주', nameEn: 'Jeju',
    districts: [
      { name: '제주시', nameEn: 'Jeju-si' },
      { name: '서귀포시', nameEn: 'Seogwipo-si' },
    ],
  },
};

export const SIDO_CODES = Object.keys(ELECTION_DISTRICTS);

export const ELECTION_TYPES = [
  'metropolitan_mayor',
  'metropolitan_council',
  'local_mayor',
  'local_council',
  'superintendent',
] as const;

export type ElectionType = typeof ELECTION_TYPES[number];

export const PLATFORM_CHAR_LIMITS: Record<string, number> = {
  instagram: 2200,
  facebook: 63206,
  x: 280,
  kakaostory: 2048,
  blog_naver: 50000,
};
